from enum import Enum


class DominoNucleusLibAuthPrincipalWithFeatureFlagsAllowedSystemOperationsItem(str, Enum):
    ACTASPROJECTADMIN = "ActAsProjectAdmin"
    CURATEPROJECTS = "CurateProjects"
    EDITCENTRALCONFIG = "EditCentralConfig"
    EDITENVIRONMENTSASOWNER = "EditEnvironmentsAsOwner"
    EXECUTERUNSFORFREE = "ExecuteRunsForFree"
    GENERATEPASSWORDRESETLINKS = "GeneratePasswordResetLinks"
    LISTALLPROJECTS = "ListAllProjects"
    MANAGEBUILDS = "ManageBuilds"
    MANAGEENVIRONMENTS = "ManageEnvironments"
    MANAGEEXECUTORS = "ManageExecutors"
    MANAGEFEATUREFLAGS = "ManageFeatureFlags"
    MANAGEHARDWARETIERS = "ManageHardwareTiers"
    MANAGEORGANIZATIONS = "ManageOrganizations"
    MANAGEPROJECTTAGS = "ManageProjectTags"
    PREVIEWPROJECTS = "PreviewProjects"
    READKUBERNETES = "ReadKubernetes"
    RESETINDEX = "ResetIndex"
    RESTARTNUCLEUS = "RestartNucleus"
    RUNMONGODBCOMMANDS = "RunMongoDBCommands"
    SETUSERSYSTEMROLES = "SetUserSystemRoles"
    STOPRUNS = "StopRuns"
    STOPSERVER = "StopServer"
    TRIGGERSEARCHINDEXING = "TriggerSearchIndexing"
    UPDATEUSER = "UpdateUser"
    USEK8SDASHBOARD = "UseK8sDashboard"
    VIEWADMINDASHBOARD = "ViewAdminDashboard"
    VIEWADMINMENU = "ViewAdminMenu"
    VIEWEVERYTHINGINCONTROLCENTER = "ViewEverythingInControlCenter"
    VIEWEXECUTORS = "ViewExecutors"
    VIEWGLOBALENVIRONMENTS = "ViewGlobalEnvironments"
    VIEWMETRICS = "ViewMetrics"
    VIEWPROJECTLIST = "ViewProjectList"
    VIEWPROJECTSIZES = "ViewProjectSizes"
    VIEWREVENUE = "ViewRevenue"
    VIEWSEARCHINDEX = "ViewSearchIndex"
    VIEWUSAGE = "ViewUsage"
    VIEWUSERLIST = "ViewUserList"

    def __str__(self) -> str:
        return str(self.value)
