name: Build docker image on push

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.ref_name }}
    - name: Build the Docker image
      run: git branch --show-current && echo "FROM python:3.10-slim-bullseye" | cat - Dockerfile | docker build -
