name: Build docker image on push

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v6
    - name: Build the Docker image
      run: |
        echo "FROM python:3.10-slim-bullseye" | cat - Dockerfile | docker build \
            --build-arg EXTENSION_VERSION=${{ github.ref_name }} \
            --build-arg GITHUB_ORG=${{ github.repository_owner }} \
            -
